### ISSUE TITLE
Create relative the current file

### ISSUE THREAD

**Issue by svenax** [patbenatar/vscode-advanced-new-file#25]
Too bad that VS Code does not yet support path completion. Let's hope that it will soon ...

As a convenience, maybe you'd like to implement the same shortcut the extension in Sublime Text uses:

- Type a path starting with a colon, and the file or folder will be created right away relative the currently open file.
or
- Type colon and return to select the directory of the current file, and then input a relative path as usual.
or
- Maybe even better, provide an option to have the directory of the current file preselected in the path selector so you just have to type return to go there.

This would be very conveninent for my workflow, since I almost always want to create new files close to the currently edited file.

**Comment by Kaffiend** [comment]
the last option seems the most friendly with it highlighted, enter again to repeat directory, just type for new directory?

**Comment by patbenatar** [comment]
@Kaffiend @svenax thoughts on the below? (this is based off of @Kaffiend 's #26 )

I'm thinking make it default behavior, rather than behind an option.

<img width="599" alt="screen shot 2017-07-04 at 9 39 19 am" src="https://user-images.githubusercontent.com/453695/27838023-cd3d40d8-609c-11e7-954f-846034ffe289.png">

**Comment by svenax** [comment]
That looks perfect to me. Thumbs up!

**Comment by Kaffiend** [comment]
I like it and find it more useful

**Comment by patbenatar** [comment]
Just released 0.5.0
