### ISSUE TITLE
absolute path + new dir/file.ext

### ISSUE THREAD

**Issue by rouzbeh84** [patbenatar/vscode-advanced-new-file#57]
Not sure if this is the default behavior or a VSCode limitation but when write an absolute path to add a new folder as well as file it does not create the dir or file. When i use the helper paths like 'relative' it creates both dir/file. 

Here is a quick gif of what's happening. At the end i'm repeatedly hitting enter but nothing is happening. 

![no new dir on enter in absolute path](https://dha4w82d62smt.cloudfront.net/items/1j112E0z340b1Y0U2s1F/Screen%20Recording%202018-04-11%20at%2006.39%20PM.gif?X-CloudApp-Visitor-Id=1667085&v=119ec961)

**Comment by patbenatar** [comment]
@rouzbeh84 this isn't a bug, but an unfortunate usability pitfall due to how this plugin works within the limitations of the UI controls available to VS Code plugins.

Every time you launch the plugin, the first step is to select the directory from which you want to create relative to. Then you're presented with a new dialog that allows you to input the new file location relative to that previously selected directory. VS Code doesn't have any kind of text input that allows "type-ahead" recommendations, so we have to split the workflow (see https://github.com/Microsoft/vscode/issues/426).

In your gif, it looks like you're trying to input the new file location on the screen where you should be selecting an existing directory to create relative to.

Does that make sense?

**Comment by rouzbeh84** [comment]
Oh ok, Maybe I poorly described it my issue. The first half of what it shows works great but the second bit is why i opened this. 

Basically if i type in an absolute path that includes a directory it doesn't do anything when hitting enter and fails 'silently.' I know it didn't work due to the input still being available but otherwise am not sure why this would work differently than when making a new file in a new directory in the 'relative' way it shows in the first half of the gif.

Does that make sense?

**Comment by patbenatar** [comment]
@rouzbeh84 I think we're misunderstanding one another. Unless if you see "Relative to [path]" below the text input, the only thing you can do is select from the paths in your project. Once you've selected, you'll then see a new input with "Relative to [path]" written below it, at which point you can type any path to create the new file/dir. In your gif, you're trying to type `/Test2/test2.js` in the directory picker, but that isn't an existing directory. What you need to do is first select a directory (in this case it might be `/` if you want to create a new dir called `Test2` relative to the root of your project) before typing `/Test2/test2.js`.

**Comment by rouzbeh84** [comment]
got it! same page now thanks! so basically always have to select the root path at some point. perfect! thanks for clearing up.

**Comment by patbenatar** [comment]
@rouzbeh84 yeah.. I'd really like to be able to support the interaction you're making in that gif but I don't think it's doable until we have https://github.com/Microsoft/vscode/issues/426
